Numpy is used to create multidimensional arrays and has multiple inbuild function which would help you to perform different kind of array oprerations.
Numpy is array processing package and provides high performance multi dimensional array and tools to working with this arrays.

Array is a datastructure data stores the values of same data type. Difference between lists and arrays is lists can contain values corresponding to different data types whereas arrays has values with the same data type.

In [1]:
#pip install numpy
!pip install jupyter_contrib_nbextensions
!jupyter contrib nbextension install --user

Traceback (most recent call last):
  File "C:\Users\aishp\anaconda3\Lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line 6, in <module>
    from notebook.extensions import BaseExtensionApp
ModuleNotFoundError: No module named 'notebook.extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\aishp\anaconda3\Lib\site-packages\jupyter_contrib_core\notebook_compat\nbextensions.py", line 10, in <module>
    from notebook.nbextensions import BaseNBExtensionApp
ModuleNotFoundError: No module named 'notebook.nbextensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aishp\anaconda3\Scripts\jupyter-contrib.EXE\__main__.py", line 7, in <module>
  File "C:\Users\aishp\anaconda3\Lib\site-packages\jupyter_core\applicat

In [2]:
%config Completer.use_jedi = False


In [3]:
import numpy as np

In [4]:
#lets create a list
list_1 = [1,2,3,4,5]
#create array from list
arr_1 = np.array(list_1)
arr_1

array([1, 2, 3, 4, 5])

In [5]:
#check the datatype of array
type(arr_1)

numpy.ndarray

In [6]:
print(arr_1) 
arr_1

[1 2 3 4 5]


array([1, 2, 3, 4, 5])

Above array is one dimensional array

In [7]:
# To check dimensionality of array -it shows you how many number of rows and columns your array have.

arr_1.shape

(5,)

In [8]:
#Multidimensional array

l1= [1,2,3,4,5]
l2= [6,7,8,9,10]
l3= [11,12,13,14,15]

arr_2 = np.array([l1,l2,l3])
arr_2


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [9]:
arr_2.shape  #- first number reoresents no. of rows and next number represents no.of columns

(3, 5)

In [10]:
# Change the shape of array

arr_2.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [11]:
arr_2.shape

(3, 5)

Now here the shape is still (3,5), becasue i didnt store the reshaped array into new array, so shape of original array remained the same

In [12]:
# Lets store reshaped array into new array 
arr_2 = arr_2.reshape(5,3)
arr_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [13]:
arr_2.shape #now the shape has got changed

(5, 3)

# How to retrieve the data from Array -indexing

In [14]:
arr_1  #Index starts from 0

array([1, 2, 3, 4, 5])

In [15]:
arr_1[3]

4

In [16]:
arr_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [17]:
# How to retrive data from here

arr_2[:,:] #-Here : colon in 1st place would retrieve all rows and colon in 2nd place would retrieve all columns

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [18]:
arr_2[0:2,0:2] #here i used 2 because index would go till (index I provided)-1

array([[1, 2],
       [4, 5]])

In [19]:
arr_2[3,2]

12

In [20]:
arr_2[1:,1:]

array([[ 5,  6],
       [ 8,  9],
       [11, 12],
       [14, 15]])

# Different inbuild functions present in numpy

## Arange

In [21]:
#np.arange(start,stop,step )

np.arange(0,10,2) #- 

array([0, 2, 4, 6, 8])

## Linspace

In [22]:
#np.linspace(start, stop, how many points you want from the given range)

np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## Copy function and broadcasting

In [23]:
arr_1[3:]=100
arr_1

array([  1,   2,   3, 100, 100])

In [24]:
arr_4 = arr_1
arr_4

array([  1,   2,   3, 100, 100])

In [25]:
arr_4[3:]=500

In [26]:
arr_4

array([  1,   2,   3, 500, 500])

In [27]:
arr_1

array([  1,   2,   3, 500, 500])

### so here arrays are reference types cause if you copy original array into second other array , and make changes in second array, those same changes would reflect in original array as well. In value type, this thing would not happen, original data would remain intact , it would not get changed.

In [28]:
# Hence, we are going to use copy function here, as it would solve above issue.

arr_5 = arr_1.copy()


In [29]:
arr_5

array([  1,   2,   3, 500, 500])

In [30]:
arr_5[3:]=200
arr_5

array([  1,   2,   3, 200, 200])

In [31]:
arr_1

array([  1,   2,   3, 500, 500])

In [32]:
val=2
arr_1<2

array([ True, False, False, False, False])

In [33]:
arr_1*2

array([   2,    4,    6, 1000, 1000])

In [34]:
arr_1[arr_1>val]

array([  3, 500, 500])

In [35]:
arr_2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [36]:
arr_2_new = arr_2.reshape(3,5)

In [37]:
arr_2*arr_2_new  #we cannot multiply arrays of different shapes.

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [ ]:
arr_1

In [ ]:
arr_4

In [ ]:
arr_1*arr_4  # here both arrays have same shape, so they can be multiplied.

In [ ]:
np.ones(4,dtype=int) # default dtype is float

In [ ]:
np.ones((2,3))

In [ ]:
# random distribution
np.random.rand(2,10)

In [39]:
np.random.randn(4) #gives numbers from standard normal distribution

array([-0.28981256,  1.12822389, -0.80610583, -0.07203641])

In [38]:
np.random.randn(4,4) #gives numbers from standard normal distribution

array([[-1.03951213e+00,  1.98174070e+00,  9.30733821e-01,
        -1.78369472e-01],
       [ 1.22939932e+00, -1.22087525e+00, -3.55360351e-01,
        -3.53316721e-01],
       [-7.32437808e-01,  3.15905340e-01,  9.19304365e-01,
         2.57848165e-01],
       [-6.26755404e-01, -1.22405159e-03, -1.18414610e+00,
         2.41921358e-01]])

In [ ]:
np.random.randint(1,100,30).reshape(15,2)

In [ ]:
np.random.random_sample(10)

In [ ]:
np.pi  #it would give you pi value

In [40]:
np.linspace(100, 150, 61)

array([100.        , 100.83333333, 101.66666667, 102.5       ,
       103.33333333, 104.16666667, 105.        , 105.83333333,
       106.66666667, 107.5       , 108.33333333, 109.16666667,
       110.        , 110.83333333, 111.66666667, 112.5       ,
       113.33333333, 114.16666667, 115.        , 115.83333333,
       116.66666667, 117.5       , 118.33333333, 119.16666667,
       120.        , 120.83333333, 121.66666667, 122.5       ,
       123.33333333, 124.16666667, 125.        , 125.83333333,
       126.66666667, 127.5       , 128.33333333, 129.16666667,
       130.        , 130.83333333, 131.66666667, 132.5       ,
       133.33333333, 134.16666667, 135.        , 135.83333333,
       136.66666667, 137.5       , 138.33333333, 139.16666667,
       140.        , 140.83333333, 141.66666667, 142.5       ,
       143.33333333, 144.16666667, 145.        , 145.83333333,
       146.66666667, 147.5       , 148.33333333, 149.16666667,
       150.        ])